language: java
sudo: false


cache:
  directories:
  - "$HOME/.m2"

before_cache:
  - rm -rf $HOME/.m2/repository/com/autentia/traviscodacy

before_install:
  - sudo apt-get install jq
  


jdk:
  - oraclejdk8


